### ISSUE TITLE
Pipes?

### ISSUE THREAD

**Issue by gurpal2000** [asyncmax/pshell#2]
Does this support pipes?

**Comment by asyncmax** [comment]
If you are asking about piping child process' output to a stream, pshell doesn't support it (yet). Otherwise, please explain more about your use case.

**Comment by gurpal2000** [comment]
OK. My use case was say a powershell command with "--- | Convert-to-json".
Ironically, in the end I don't need piping anyway.

**Comment by asyncmax** [comment]
Right, you don't need piping in pshell layer for that use case.
